#!/bin/bash

#echo pico_w
#openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000"

echo pico2_w
$HOME/.pico-sdk/openocd/0.12.0+dev/openocd -s $HOME/.pico-sdk/openocd/0.12.0+dev/scripts -f interface/cmsis-dap.cfg -f target/rp2350.cfg -c "adapter speed 1000" -c "rp2350.dap.core1 cortex_m reset_config sysresetreq"

